import type { Express } from 'express';
// This will be auto-generated by TSOA when you run npm run build
import { RegisterRoutes } from './routes';

export function registerRoutes(app: Express) {
    // Use TSOA's auto-generated routes
    RegisterRoutes(app);
}